# Seats on the stadium.
# There are three categories of seating in the stadium.
# Class A seats $20, Class B seats $15, and Class C seats $10. Write a program 
# that asks how many tickets of each class have been
# sold, and then outputs the amount of revenue generated by ticket sales.
A_CLASS = 20 # ticket price
B_CLASS = 15 # ticket price
C_CLASS = 10 # ticket price

def main():
    a_class_sold =int(input("Enter the quantity of A-class tickets sold: ")) 
    b_class_sold =int(input("Enter the quantity of B-class tickets sold: ")) 
    c_class_sold =int(input("Enter the quantity of C-class tickets sold: ")) 
    total_revenue = a_class_total(a_class_sold) + b_class_total(b_class_sold) + c_class_total(c_class_sold)
    print(f"A-class tickets sold for the amount of $ {a_class_total(a_class_sold):,.2f}")
    print(f"B-class tickets sold for the amount of $ {b_class_total(b_class_sold):,.2f}")
    print(f"C-class tickets sold for the amount of $ {c_class_total(c_class_sold):,.2f}")
    print(f"Total revenue ${total_revenue:,.2f}")

def a_class_total(tickets):
    total = tickets * A_CLASS
    return total

def b_class_total(tickets):
    total = tickets * B_CLASS
    return total

def c_class_total(tickets):
    total = tickets * C_CLASS
    return total
    
main()